### ISSUE TITLE
请问同款lab压缩文件在哪里下载

### ISSUE THREAD

**Issue by Henry-qing** [zhuozhiyongde/Introduction-To-Computer-System-2023Fall-PKU#2]
我去cmu官网上找到的里面第一个datalab的题目和大佬您博客里不太一样诶，想问问这个压缩文件可以在哪里下载

**Comment by zhuozhiyongde** [comment]
https://github.com/01-Data-Lab/datalab-handout.tar

各个文件夹里这种带 handout 的就是
