### ISSUE TITLE
BOMBLAB phase_5的问题

### ISSUE THREAD

**Issue by xiaoqiufeng123** [zhuozhiyongde/Introduction-To-Computer-System-2023Fall-PKU#3]
![cd7e9a3873f2dd2e91fe346a047b5d1](https://github.com/user-attachments/assets/858f3616-4ecc-4df3-9d29-a510bb4e10ec)
学长您好，我这个phase_5在按照您的教程做了后，
![3079a76b15cd0ce573448672bbdb34e](https://github.com/user-attachments/assets/10c0dd90-0c75-4ba1-9b4c-dcec47450764)
得到的是这样的结果，是为什么呀，┭┮﹏┭┮

**Comment by zhuozhiyongde** [comment]
自己多试试，每年的题不一样，同一年题也会有所不同、、、
我的教程只是一个参考的作用，目的不是帮你把 Lab 写完...
